version: '2'

services:

  php5.6-apache.dev:
    restart: always
    image: yousan/php5.6-apache:1.0
    ports:
      - 80:80
#      - 9000:9000
    volumes:
      - ./php5.6-apache-php:/tmp/php/
      # Add symlink directories if you use symlinks at documents.
#      - ~/git:/Users/yousan/git
#      - ~/svn:/Users/yousan/svn
      - ~/public/:/var/www/vhosts/test.dev
    environment:
      PMA_HOST: mysql.dev
      PMA_USER: root
      PMA_PASSWORD: example

  mysql.dev:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306
    volumes:
      - /private/var/lib/mysql:/var/lib/mysql

  dnsmasq.dev:
    image: yousan/dnsmasq
    ports:
      - 53:53/tcp
      - 53:53/udp
    cap_add:
      - NET_ADMIN
