# @link http://qiita.com/pine613/items/9ddea9ca89a1b51fcba8
# @link https://github.com/masutaka/github-organization-watcher/pull/48/files
# @link https://circleci.com/docs/2.0/sample-config/
# @link https://circleci.com/docs/2.0/configuration-reference/#storetestresults

version: 2
jobs:
  build:
    working_directory: ~/docker
    docker:
      - image: docker:17.03-git

    steps:
      - checkout
      - setup_remote_docker
      - run: apk add --update py-pip curl
      - run: pip install docker-compose
      - run: echo 'nameserver 127.0.0.1' > /etc/resolv.conf
      - run: ls
      - run: pwd -P
      - run: docker-compose up -d
      - run: docker ps
      - run: docker-compose ps
#      - run: ping -c 1 test.dev
#      - run: curl http://127.0.0.1/index.html
      - run: curl http://php5.6-apache.dev/index.html